title: What I'm Up To
description: List of things I've been working on or been involved with.
author: Noah Curran
github: https://github.com/noah-curran
about: Purdue University, Undergraduate Research Assistant
disqus_shortname: noahcurran
google_analytics: UA-141570357-1
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/SwimNoah113"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/noah-curran/"
    - icon: fa-github
      link: "https://github.com/noah-curran"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://noah-curran.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
